# Generated by Django 4.2.1 on 2024-04-21 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес филиала')),
                ('short_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткое название филиала')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отдела')),
                ('storey', models.IntegerField(verbose_name='Этаж')),
                ('name_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch', verbose_name='Название филиала')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('position', models.CharField(max_length=25, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=35, null=True, verbose_name='Номер телефон')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('name_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Название отдела')),
            ],
        ),
    ]
